spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate  # ou "update" se quiser manter dados entre execuções
server:
  port: ${PORT:8080}
  spring:
    profiles:
      active: ${SPRING_PROFILES_ACTIVE:prd} #